# Generated by Django 4.2.5 on 2023-10-02 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lottery", "0001_initial"),
        ("ballot", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="lottery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="lottery",
                to="lottery.lottery",
            ),
        ),
    ]
