# Generated by Django 4.2.5 on 2023-10-02 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("ballot", "0003_alter_ballot_lottery"),
    ]

    operations = [
        migrations.AddField(
            model_name="ballot",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
