# Generated by Django 4.2.5 on 2023-10-03 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("lottery", "0003_rename_ballot_lottery_ballots"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ballot", "0004_ballot_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ballot",
            name="lottery",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lottery",
                to="lottery.lottery",
            ),
        ),
        migrations.AlterField(
            model_name="ballot",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
